#!/usr/bin/env python3
"""Embed the canonical verifier and public trust anchor in the trusted installer.

The first installer is itself a trust bootstrap, obtained out of band. Later
updates authenticate this installer with the key in the installed package.
Never replace the public anchor with a key fetched alongside a release.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parent.parent
BEGIN = "# BEGIN GENERATED RELEASE VERIFIER - DO NOT EDIT"
END = "# END GENERATED RELEASE VERIFIER"


def source_text(path: Path) -> str:
    text = path.read_bytes().decode("utf-8").replace("\r\n", "\n")
    if "\r" in text or "\0" in text:
        raise ValueError(f"Invalid control character in {path}")
    return text.rstrip("\n") + "\n"


def generated_block(verifier: str, public_key: str) -> str:
    if not verifier.startswith("#!/bin/sh\n"):
        raise ValueError("The canonical verifier must be a POSIX shell script")
    if not (public_key.startswith("-----BEGIN PUBLIC KEY-----\n") and
            public_key.endswith("-----END PUBLIC KEY-----\n")):
        raise ValueError("Expected a public-key PEM trust anchor, never a private key")
    verifier_end = "KEEN_PBR_RELEASE_VERIFIER_EOF"
    key_end = "KEEN_PBR_RELEASE_PUBLIC_KEY_EOF"
    for delimiter in (verifier_end, key_end):
        if delimiter in verifier.splitlines() or delimiter in public_key.splitlines():
            raise ValueError("Embedded source collides with its heredoc delimiter")
    return (
        BEGIN + "\n"
        "# Generated by build_scripts/embed-release-verifier.py.\n"
        "# First-install trust comes from this installer, not downloaded metadata.\n"
        "prepare_release_verifier() {\n"
        '    RELEASE_VERIFIER="$TMP_DIR/release-verify.sh"\n'
        '    RELEASE_PUBLIC_KEY="$TMP_DIR/release-public.pem"\n'
        f'    cat > "$RELEASE_VERIFIER" <<\'{verifier_end}\'\n'
        + verifier + verifier_end + "\n"
        f'    cat > "$RELEASE_PUBLIC_KEY" <<\'{key_end}\'\n'
        + public_key + key_end + "\n"
        '    chmod 0600 "$RELEASE_VERIFIER" "$RELEASE_PUBLIC_KEY"\n'
        "}\n"
        + END
    )


def embed(installer: str, block: str) -> str:
    if installer.count(BEGIN) != 1 or installer.count(END) != 1:
        raise ValueError("Installer must contain exactly one canonical verifier block")
    start = installer.index(BEGIN)
    end = installer.index(END)
    if start > end:
        raise ValueError("Installer verifier markers are out of order")
    return installer[:start] + block + installer[end + len(END):]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--installer", type=Path, default=ROOT / "install.sh")
    parser.add_argument("--verifier", type=Path, default=ROOT /
                        "packages/keenetic/keen-pbr/files/opt/usr/lib/keen-pbr/release-verify.sh")
    parser.add_argument("--public-key", type=Path, default=ROOT /
                        "packages/keys/keenetic-release-public.pem")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        installer = source_text(args.installer)
        result = embed(installer, generated_block(source_text(args.verifier),
                                                  source_text(args.public_key)))
        if args.check:
            if args.installer.read_bytes() != result.encode("utf-8"):
                raise ValueError("Embedded release verifier/key is stale; run the generator")
        else:
            args.installer.write_bytes(result.encode("utf-8"))
    except (OSError, UnicodeError, ValueError) as error:
        print(f"release verifier embedding: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
