#include <doctest/doctest.h>

#include "../src/keenetic/ndms_native_secret_snapshot.hpp"

#include <cerrno>
#include <filesystem>
#include <fstream>
#include <string>
#include <system_error>
#include <vector>

#include <sys/stat.h>
#include <unistd.h>

namespace keen_pbr3 {

namespace {

namespace fs = std::filesystem;

class TempDirectory {
public:
    TempDirectory() {
        std::string pattern =
            (fs::temp_directory_path() / "keen-pbr-secret-XXXXXX").string();
        std::vector<char> writable(pattern.begin(), pattern.end());
        writable.push_back('\0');
        const char* created = ::mkdtemp(writable.data());
        REQUIRE(created != nullptr);
        path = created;
    }

    ~TempDirectory() {
        std::error_code error;
        fs::remove_all(path, error);
    }

    fs::path path;
};

const std::string kTransaction(32U, 'a');
const std::string kMarker = "kpbr-ni-v1-" + kTransaction;
const std::string kSecret =
    "PrivateKey = 2BJtA3H8tWH+4Wsg1CmSbdaUcVXK/HeNTIEnyZ2W3Vw=";

NdmsNativeSecretSnapshotStore store_for(const TempDirectory& directory) {
    return NdmsNativeSecretSnapshotStore(
        directory.path / "keys" / "master.key",
        directory.path / "snapshots");
}

} // namespace

TEST_CASE("a sealed secret comes back only under its exact identity") {
    TempDirectory directory;
    auto store = store_for(directory);
    store.publish("Wireguard5", kTransaction, kMarker, kSecret);

    const auto read = store.read("Wireguard5", kTransaction, kMarker);
    REQUIRE(read.state == NdmsNativeSecretReadState::valid);
    CHECK(*read.secret == kSecret);

    // A different transaction, a different marker: the ciphertext is bound
    // to the identity it was sealed for, not to the file it sits in.
    const std::string other(32U, 'b');
    CHECK(store.read("Wireguard5", other, "kpbr-ni-v1-" + other).state ==
          NdmsNativeSecretReadState::unreadable);
}

TEST_CASE("a snapshot renamed onto another interface does not decrypt") {
    TempDirectory directory;
    auto store = store_for(directory);
    store.publish("Wireguard6", kTransaction, kMarker, kSecret);

    std::error_code error;
    fs::rename(directory.path / "snapshots" / "Wireguard6",
               directory.path / "snapshots" / "Wireguard5", error);
    REQUIRE_FALSE(error);
    // The name is part of the authenticated data: a copied or renamed
    // snapshot asserts a key for an interface it never held.
    CHECK(store.read("Wireguard5", kTransaction, kMarker).state ==
          NdmsNativeSecretReadState::unreadable);
}

TEST_CASE("tampered bytes and torn files read as damage, never absence") {
    TempDirectory directory;
    auto store = store_for(directory);
    store.publish("Wireguard5", kTransaction, kMarker, kSecret);
    const auto path = directory.path / "snapshots" / "Wireguard5";

    auto tamper = [&](const std::size_t offset) {
        std::fstream file(path,
                          std::ios::binary | std::ios::in | std::ios::out);
        REQUIRE(file);
        file.seekg(0, std::ios::end);
        const auto size = static_cast<std::size_t>(file.tellg());
        REQUIRE(offset < size);
        file.seekp(static_cast<std::streamoff>(offset));
        char byte = 0;
        file.seekg(static_cast<std::streamoff>(offset));
        file.read(&byte, 1);
        file.seekp(static_cast<std::streamoff>(offset));
        byte = static_cast<char>(byte ^ 0x01);
        file.write(&byte, 1);
    };

    tamper(40U);  // inside the ciphertext
    CHECK(store.read("Wireguard5", kTransaction, kMarker).state ==
          NdmsNativeSecretReadState::unreadable);

    std::ofstream torn(path, std::ios::binary | std::ios::trunc);
    torn << "keen-pbr-secret-snapshot-v1\n";
    torn.close();
    CHECK(store.read("Wireguard5", kTransaction, kMarker).state ==
          NdmsNativeSecretReadState::unreadable);
}

TEST_CASE("a lost master key is damage that reaches a human, not absence") {
    TempDirectory directory;
    auto store = store_for(directory);
    store.publish("Wireguard5", kTransaction, kMarker, kSecret);

    std::error_code error;
    fs::remove(directory.path / "keys" / "master.key", error);
    REQUIRE_FALSE(error);

    // The snapshot exists and its key does not. Absence here would tell a
    // mutation "proceed, there is nothing to preserve" - over a secret that
    // is still on disk and merely locked.
    CHECK(store.read("Wireguard5", kTransaction, kMarker).state ==
          NdmsNativeSecretReadState::unreadable);
    // And the key is not silently regenerated by the read.
    CHECK_FALSE(fs::exists(directory.path / "keys" / "master.key", error));
}

TEST_CASE("a corrupt master key is never replaced by publish") {
    TempDirectory directory;
    auto store = store_for(directory);
    store.publish("Wireguard5", kTransaction, kMarker, kSecret);

    std::ofstream corrupt(directory.path / "keys" / "master.key",
                          std::ios::binary | std::ios::trunc);
    corrupt << "short";
    corrupt.close();

    // Regenerating would orphan every snapshot sealed under the old key.
    CHECK_THROWS(
        store.publish("Wireguard6", kTransaction, kMarker, kSecret));
}

TEST_CASE("two seals of one secret share no bytes beyond the header") {
    TempDirectory directory;
    auto store = store_for(directory);
    store.publish("Wireguard5", kTransaction, kMarker, kSecret);
    std::string first;
    {
        std::ifstream input(directory.path / "snapshots" / "Wireguard5",
                            std::ios::binary);
        first.assign((std::istreambuf_iterator<char>(input)),
                     std::istreambuf_iterator<char>());
    }
    store.publish("Wireguard5", kTransaction, kMarker, kSecret);
    std::string second;
    {
        std::ifstream input(directory.path / "snapshots" / "Wireguard5",
                            std::ios::binary);
        second.assign((std::istreambuf_iterator<char>(input)),
                      std::istreambuf_iterator<char>());
    }
    // A repeated nonce under one key breaks the cipher's whole guarantee;
    // fresh kernel randomness per seal means two seals of identical plaintext
    // may not repeat their nonce or their ciphertext.
    REQUIRE(first.size() == second.size());
    CHECK(first.substr(28U, 12U) != second.substr(28U, 12U));
    CHECK(first.substr(40U) != second.substr(40U));
}

TEST_CASE("protected slots and malformed identities cannot hold secrets") {
    TempDirectory directory;
    auto store = store_for(directory);
    for (const char* name :
         {"Wireguard0", "Wireguard99", "wireguard5", "Wireguard05"}) {
        CHECK_THROWS(store.publish(name, kTransaction, kMarker, kSecret));
        CHECK(store.read(name, kTransaction, kMarker).state ==
              NdmsNativeSecretReadState::unreadable);
    }
    CHECK_THROWS(
        store.publish("Wireguard5", kTransaction, kMarker, ""));
}

TEST_CASE("remove_exact removes only what still decrypts as this identity") {
    TempDirectory directory;
    auto store = store_for(directory);
    store.publish("Wireguard5", kTransaction, kMarker, kSecret);

    const std::string other(32U, 'b');
    CHECK_FALSE(
        store.remove_exact("Wireguard5", other, "kpbr-ni-v1-" + other));
    CHECK(store.read("Wireguard5", kTransaction, kMarker).state ==
          NdmsNativeSecretReadState::valid);

    CHECK(store.remove_exact("Wireguard5", kTransaction, kMarker));
    CHECK(store.read("Wireguard5", kTransaction, kMarker).state ==
          NdmsNativeSecretReadState::absent);
    CHECK_FALSE(store.remove_exact("Wireguard5", kTransaction, kMarker));
}

TEST_CASE("the key and the snapshots are private on disk") {
    TempDirectory directory;
    auto store = store_for(directory);
    store.publish("Wireguard5", kTransaction, kMarker, kSecret);

    struct stat info {};
    REQUIRE(::lstat((directory.path / "keys" / "master.key").c_str(),
                    &info) == 0);
    CHECK((info.st_mode & 07777) == 0600U);
    REQUIRE(::lstat((directory.path / "snapshots" / "Wireguard5").c_str(),
                    &info) == 0);
    CHECK((info.st_mode & 07777) == 0600U);
}

} // namespace keen_pbr3
