#pragma once

#include <cstdint>
#include <memory>
#include <optional>
#include <stdexcept>
#include <string>
#include <vector>

#include "../util/traced_mutex.hpp"

namespace keen_pbr3 {

namespace netlink_detail {

enum class InterfaceAdminState {
    Unknown,
    Missing,
    Down,
    Up,
};

// Lightweight last-moment readiness check for route installation. TUN and
// WireGuard links frequently report an unknown operstate or no carrier, so
// administrative IFF_UP is the only portable requirement here.
InterfaceAdminState query_interface_admin_state(
    const std::string& interface_name) noexcept;

// libnl reports removal of an object that the kernel already discarded as an
// error. Route deletion is idempotent, so these codes mean the requested
// postcondition has already been reached.
bool route_delete_target_absent(int error_code) noexcept;

} // namespace netlink_detail

class NetlinkError : public std::runtime_error {
public:
    using std::runtime_error::runtime_error;
};

// A route could not be installed because its output interface disappeared or
// is not administratively ready.  Keeping this distinct from permanent
// netlink/configuration failures lets the reconciler defer only transient
// repairs without weakening transactional application of new routes.
class RouteInterfaceUnavailableError : public NetlinkError {
public:
    using NetlinkError::NetlinkError;
};

enum class RouteType {
    unicast,
    blackhole,
    unreachable
};

// Reserved RTPROT value for routes generated by keen-pbr. Future
// reconciliation uses it to distinguish managed state from native routes.
#ifndef KEEN_PBR_ROUTE_PROTOCOL
#define KEEN_PBR_ROUTE_PROTOCOL 186
#endif
constexpr uint8_t KEEN_PBR_GENERATED_ROUTE_PROTOCOL = KEEN_PBR_ROUTE_PROTOCOL;

// Represents a route to install in the kernel
struct RouteSpec {
    std::string destination;    // IP/CIDR (e.g., "10.0.0.0/8") or "default"
    uint32_t table{0};          // Routing table ID (0 = main)
    std::optional<std::string> interface;   // Output interface name
    std::optional<std::string> gateway;     // Next-hop gateway IP
    bool blackhole{false};      // If true, create a blackhole route
    bool unreachable{false};    // If true, create an unreachable route
    int family{0};              // AF_INET or AF_INET6 (0 = auto-detect)
    uint32_t metric{0};         // Route metric/priority (0 = kernel default)
    uint8_t protocol{KEEN_PBR_GENERATED_ROUTE_PROTOCOL};
};

enum class RouteAddResult {
    Created,
    AlreadyPresent,
};

// Receipt for an exact RTM_DELROUTE request.  PreconditionMismatch means the
// backend cannot prove that the object occupying the kernel slot is the exact
// expected image, so no destructive request was sent.
enum class RouteExactDeleteResult {
    Deleted,
    AlreadyAbsent,
    PreconditionMismatch,
};

enum class RouteExactReplaceResult {
    Replaced,
    PreconditionMismatch,
};

struct DumpedRoute;

// Small testable surface used by RouteTable.  Returning whether the kernel
// object was created is essential: cleanup must never delete a route that
// predated this process.
class RouteNetlinkOperations {
public:
    virtual ~RouteNetlinkOperations() = default;
    // A combined exact transaction may perform rollback after any forward
    // write. Returning true is a strong lease assertion: this same most-
    // derived backend exclusively serializes the complete route + policy-rule
    // dependency namespace for the full execute call and implements every
    // conditional primitive below. A mere per-socket mutex is insufficient.
    virtual bool supports_exact_route_transaction() const noexcept {
        return false;
    }
    virtual RouteAddResult add_route(const RouteSpec& spec) = 0;
    // Atomically replace the route occupying the same kernel slot. Callers
    // must first prove that the conflicting object is keen-pbr-owned (route
    // protocol 186); NetlinkManager deliberately does not infer ownership.
    virtual void replace_route(const RouteSpec& spec) = 0;
    virtual void delete_route(const RouteSpec& spec) = 0;
    // Transactional callers must use this surface.  The safe default refuses
    // deletion; concrete backends which can submit the full route identity
    // atomically may override it and return a typed receipt.
    virtual RouteExactDeleteResult delete_route_if_exact(
        const RouteSpec&) {
        return RouteExactDeleteResult::PreconditionMismatch;
    }
    virtual RouteExactReplaceResult replace_route_if_exact(
        const RouteSpec&,
        const RouteSpec&) {
        return RouteExactReplaceResult::PreconditionMismatch;
    }
    virtual std::vector<DumpedRoute> dump_routes(int family = 0) = 0;
};

// Represents a policy routing rule (ip rule)
struct RuleSpec {
    uint32_t fwmark{0};         // Firewall mark to match
    uint32_t fwmask{0xFFFFFFFF}; // Firewall mark mask
    uint32_t table{0};          // Routing table to use
    uint32_t priority{0};       // Rule priority (lower = higher priority)
    int family{0};              // AF_INET or AF_INET6 (0 = both)
};

enum class RuleAddResult {
    Created,
    AlreadyPresent,
};

enum class RuleExactDeleteResult {
    Deleted,
    AlreadyAbsent,
    PreconditionMismatch,
};

struct DumpedRule;

// PolicyRuleManager expands family=0 into two concrete operations so it can
// roll IPv4 back if the matching IPv6 install fails.
class RuleNetlinkOperations {
public:
    virtual ~RuleNetlinkOperations() = default;
    // Same combined exclusive-writer lease contract as the route capability;
    // execute rejects distinct most-derived route/rule backend objects.
    virtual bool supports_exact_rule_transaction() const noexcept {
        return false;
    }
    virtual RuleAddResult add_rule_for_family(const RuleSpec& spec, int family) = 0;
    virtual void delete_rule_for_family(const RuleSpec& spec, int family) = 0;
    // Exact transactions must never fall back to the broad policy-rule delete
    // key. Backends which cannot prove and conditionally delete one complete
    // rule identity fail closed by default.
    virtual RuleExactDeleteResult delete_rule_if_exact(
        const RuleSpec&,
        int) {
        return RuleExactDeleteResult::PreconditionMismatch;
    }
    virtual std::vector<DumpedRule> dump_policy_rules(int family = 0) = 0;
};

// A route dumped from the kernel (read-only snapshot)
struct DumpedRoute {
    std::string destination;            // "default" for 0/0, else "x.x.x.x/N"
    uint32_t table{0};                  // Routing table ID
    std::optional<std::string> interface;  // Output interface name (if any)
    std::optional<std::string> gateway;    // Next-hop gateway IP (if any)
    bool blackhole{false};              // True if route type is RTN_BLACKHOLE
    bool unreachable{false};           // True if route type is RTN_UNREACHABLE
    int family{0};                      // AF_INET or AF_INET6
    uint32_t metric{0};                 // Route metric/priority
    uint8_t protocol{0};                // Kernel rtm_protocol
    // False when the kernel object has a route type or multipath shape which
    // RouteSpec cannot express exactly. Such an object may occupy a slot but
    // can never satisfy an exact ownership/commit proof.
    bool exact_identity_representable{true};
};

// A policy rule dumped from the kernel (read-only snapshot)
struct DumpedRule {
    uint32_t priority{0};
    uint32_t fwmark{0};
    uint32_t fwmask{0};
    uint32_t table{0};
    int family{0};              // AF_INET or AF_INET6
    // False when the kernel rule contains selectors or metadata which
    // RuleSpec cannot encode. Such a rule may occupy the same visible key,
    // but cannot satisfy an exact ownership/commit proof.
    bool exact_identity_representable{true};
};

// A network interface dumped from the kernel (read-only snapshot)
struct DumpedInterface {
    std::string name;                   // Interface name (e.g. "eth0")
    bool admin_up{false};              // True when IFF_UP is set
    std::optional<std::string> oper_state; // Kernel operstate label when available
    std::optional<bool> carrier;       // Link carrier state when reported by kernel
    // Exact kernel master (normally a bridge) resolved from IFLA_MASTER.
    // This is intentionally a name rather than a raw ifindex so runtime
    // policy can verify L2-to-L3 topology without a second lookup.
    std::optional<std::string> master_interface;
    std::vector<std::string> ipv4_addresses; // IPv4 addresses in CIDR form
    std::vector<std::string> ipv6_addresses; // IPv6 addresses in CIDR form
    // Remote endpoint addresses reported by IFA_ADDRESS on point-to-point
    // links. These are intentionally separate from local addresses: native
    // L2TP/SSTP/OpenConnect server peers can be admitted to dnsmasq only when
    // the live remote endpoint belongs to an authoritative NDMS client pool.
    std::vector<std::string> ipv4_peer_addresses;
    std::vector<std::string> ipv6_peer_addresses;
};

// Low-level netlink route and policy rule management via libnl
class NetlinkManager : public RouteNetlinkOperations,
                       public RuleNetlinkOperations {
public:
    NetlinkManager();
    ~NetlinkManager();

    // Non-copyable, non-movable (owns netlink socket)
    NetlinkManager(const NetlinkManager&) = delete;
    NetlinkManager& operator=(const NetlinkManager&) = delete;
    NetlinkManager(NetlinkManager&&) = delete;
    NetlinkManager& operator=(NetlinkManager&&) = delete;

    // Route operations
    RouteAddResult add_route(const RouteSpec& spec) override;
    void replace_route(const RouteSpec& spec) override;
    void delete_route(const RouteSpec& spec) override;
    RouteExactDeleteResult delete_route_if_exact(
        const RouteSpec& spec) override;
    RouteExactReplaceResult replace_route_if_exact(
        const RouteSpec& expected,
        const RouteSpec& replacement) override;
    void flush_routes_in_table(uint32_t table_id, int family = 0);

    // Policy rule operations
    RuleAddResult add_rule_for_family(const RuleSpec& spec, int family) override;
    void delete_rule_for_family(const RuleSpec& spec, int family) override;
    RuleExactDeleteResult delete_rule_if_exact(
        const RuleSpec& spec,
        int family) override;

    // Dump all routes in a specific routing table from the kernel.
    // family: 0 (AF_UNSPEC) to get both IPv4 and IPv6 routes.
    std::vector<DumpedRoute> dump_routes(int family = 0) override;
    std::vector<DumpedRoute> dump_routes_in_table(uint32_t table_id,
                                                   int family = 0);

    // Dump all policy rules from the kernel.
    // family: 0 (AF_UNSPEC) to get both IPv4 and IPv6 rules.
    std::vector<DumpedRule> dump_policy_rules(int family = 0) override;

    // Dump all network interfaces from the kernel with best-effort live detail.
    std::vector<DumpedInterface> dump_interfaces();

private:
    struct Impl;
    std::unique_ptr<Impl> impl_;
    mutable TracedMutex mutex_;
};

} // namespace keen_pbr3
